# Generated by Django 4.2.6 on 2023-10-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('Nr_doc', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=38, null=True)),
                ('Contraseña', models.CharField(max_length=38, null=True)),
                ('Id_rol', models.CharField(max_length=38, null=True)),
            ],
        ),
    ]
