# Generated by Django 4.2.6 on 2023-10-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Nombre',
        ),
    ]
