# Generated by Django 4.2.6 on 2023-10-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_usuarios_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='Direccion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Nombre',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Telefono',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
